#!/bin/bash

# PERIOD 60 means 60 packets per hour
# PERIOD 6 means 600 packets per hour

# iL = init Logs
# oL = Output Logs
# fp = fixed nodes Period
# fId = fixed nodes Idouble

#mobPer=50 #mobile Period
#fixPer=30 # fixed station Period
mobId=8 # mobile station Idouble - Usually unchanged
fid=8 # fixed station Idouble - Can play with it

#delete old log files if any
#rm COOJA.testlog
#rm COOJA.log

#start running ALL avaliable csc files
for mobPer in {40..60..10}
   do
      for fixPer in {40..60..10}
         do
            initDir='iL-mP='"$mobPer"'-fP='"$fixPer"'-fId='"$fid"
            logDir='oL-mP='"$mobPer"'-fP='"$fixPer"'-fId='"$fid"
            #mkdir $initDir
            mkdir $logDir
                  
            for filename in *.csc ;
               do
                  #echo "Passing Idouble in fixed parameter: " $fid
                  #(cd ../../../../examples/ipv6/coral-rpl-upd && exec python ./changeParams.py -mp $mobPer -fp $fixPer -fi $fid -mi $mobId) # be careful, we need the parentheses 
                  echo  
                  echo "Creating logs for: " $filename
				      #java -Xmx4096m -jar ../../../../tools/cooja/dist/cooja.jar -nogui="$filename" -contiki='../../../..'
				      #cp COOJA.testlog "$initDir"'/'"$filename"'.log' 
				
				      ./createALLlogs-new.py -r $initDir -w $logDir
				      
				      #rm COOJA.testlog
				      #rm COOJA.log
			      done	
               
               echo
			      echo "creating graphs (*.plt files) in folder: " $logDir 

               cp ./auto-PDR.plt "$logDir"
               cp ./auto-OVERHEAD.plt "$logDir"
               cp ./auto-PDR-mobs.plt "$logDir"
               # in case you want to re-create graphs, run this inside each folder
               cp ./createGraphsAgain $logDir


               #go into the folder ./logs and create the above graphs
               cd $logDir
               ./createGraphsAgain
               cd ..
         done
   done
   
#copy all PDR graphs inside folder 1.allGraphsFolder
./getAllGraphs.py
