CONTIKI_PROJECT = rtimer_TX
CONTIKI_PROJECT += rtimer_RX
all: $(CONTIKI_PROJECT)

CONTIKI = ~/contiki

CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"

CONTIKI_WITH_RIME = 1

include $(CONTIKI)/Makefile.include
