#!/bin/bash

#create folders if they dont exist
mkdir -p initial_logs
mkdir -p logs

#delete old log files if any
rm COOJA.testlog
rm COOJA.log

#start running ALL avaliable csc files
for filename in *.csc ;
	do
		for i in {1..1} 
			do 
				echo "running scenario: " $filename
				java -Xmx4096m -jar ../../../../tools/cooja/dist/cooja.jar -nogui="$filename" -contiki='../../../..'
				cp COOJA.testlog './initial_logs/'"$filename"'-'$i'.log' 
				rm COOJA.testlog
				rm COOJA.log
				echo ""
				echo "finished round:" $i
				echo ""
			done
	done


