#!/bin/bash

# execute all *csc files found.
# they have to be cooja scenarios WITHOUT GUI
./runALLcsc

# will look into folder ./initial_logs and extract
# a file in ./logs with three columns:
# first column is the time/counter (usually upto 60)
# Second column is the Packet Delivery Ratio (PDR)
# Third column is the Overhead (OH)
python createALLlogs-new.py

# running all graph creation files
# auto-PDR.plt looks for all *.log files and plots columns 1,2. 
# auto-OH.plt will do the same for columns 1,3
# the name of the graph, is the name of the folder
cp ./auto-PDR.plt ./logs/auto-PDR.plt
cp ./auto-OVERHEAD.plt ./logs/auto-OVERHEAD.plt

# in case you want to re-create graphs, run this inside each folder
cp ./createGraphsAgain ./logs/createGraphsAgain

#go into the folder ./logs and create the above graphs
cd logs/
./createGraphsAgain

